[theme]
base = "light"
primaryColor = "#85554A"
backgroundColor = "#F5F4F0"
secondaryBackgroundColor = "#E8EBE7"
textColor = "#27302C"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
